In [34]:
def axis_bank(file_name):
    import tabula
    from tabula import read_pdf
    import pandas as pd
    import numpy as np
    import re
    import operator


#     dt = pd.read_excel('IFSC codes.xls', header=0)
    
    try:
        tables=read_pdf(file_name, area=(15, 15, 320, 500), pages = 1)
        df5 = pd.DataFrame()
        df5 = pd.concat([c for c in tables]).drop_duplicates()
        df5.reset_index(drop=True, inplace=True)
        df5.dropna(axis=1, how="all", thresh=None, subset=None, inplace=True)
        df5 = pd.DataFrame(np.row_stack([df5.columns, df5.values]),columns=['1', '2'])
    except AssertionError:
        tables=read_pdf(file_name, area=(15, 15, 260, 400), pages = 1)
        df5 = pd.DataFrame()
        df5 = pd.concat([c for c in tables]).drop_duplicates()
        df5.reset_index(drop=True, inplace=True)
        df5.dropna(axis=1, how="all", thresh=None, subset=None, inplace=True)
#         df5 = pd.DataFrame(np.row_stack([df5.columns, df5.values]),columns=['1'])
    except ValueError:
        tables=read_pdf(file_name, area=(15, 15, 260, 400), pages = 1)
        df5 = pd.DataFrame()
        df5 = pd.concat([c for c in tables]).drop_duplicates()
        df5.reset_index(drop=True, inplace=True)
        df5.dropna(axis=1, how="all", thresh=None, subset=None, inplace=True)
#         df5 = pd.DataFrame(np.row_stack([df5.columns, df5.values]),columns=['1'])
    
    acc_n5 = ""; acc_n5s = ""; acc_no5 = ""; addr5 = ""; br_details5 = "";
    cifn5 = ""; ifsc5 = ""; micrn5 = "";
    line = 0
    siz = len(df5.columns)

    for j in range(0, siz):
        for count,i in enumerate(df5[df5.columns[j]]):
            try:
                if i.isupper() and acc_n5 == "":
                    acc_n5 = i
                if ("joint holder") in i.lower():
                    addr5 = (df5[df5.columns[j]][count+1]).strip(" ").strip(".").strip(":").strip(" ") + "," + (df5[df5.columns[j]][count+2]).strip(" ").strip(".").strip(":").strip(" ") + "," + (df5[df5.columns[j]][count+3]).strip(" ").strip(".").strip(":").strip(" ")+ "," + (df5[df5.columns[j]][count+4]).strip(" ").strip(".").strip(":").strip(" ")
                if ("account no") in i.lower():
                    acc = str(i.lower()).find("account no")
                    i = (i[acc+10:]).strip(" ").strip(":").strip(" ")
                    acc_no5 = i[:15]

            except AttributeError:
                pass

#     if acc_n5 != "":
#         dfr5 = pd.DataFrame([["Account Name", acc_n5]], columns = ["Customer Information", "Data_Extracted"])

    dfr5 = pd.DataFrame([["Account Name", acc_n5]], columns = ["Customer Information", "Data_Extracted"])
    dfr5.loc[len(dfr5)] = ["Account Number", acc_no5]
    dfr5.loc[len(dfr5)] = ["IFS Code", ifsc5]
    dfr5.loc[len(dfr5)] = ["Branch Name", br_details5]
    dfr5.loc[len(dfr5)] = ["Address", addr5]
    dfr5.loc[len(dfr5)] = ["MICR Code", micrn5]
    dfr5.loc[len(dfr5)] = ["CIF Number", cifn5]

    return dfr5

In [39]:
axis_bank("axis05.pdf")

  Customer Information                                     Data_Extracted
0         Account Name                                     SOURABH  MEENA
1       Account Number                                    917010083317347
2             IFS Code
3          Branch Name
4              Address  PLOT NO-214,,SANJAY NAGAR- B,,JOSHI MARG KALWA...
5            MICR Code
6           CIF Number